# Generated by Django 2.1.7 on 2019-03-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('title', models.CharField(max_length=64)),
                ('summary', models.TextField()),
                ('ip_address', models.CharField(max_length=15)),
                ('submission_date', models.DateField()),
            ],
        ),
    ]
