# Generated by Django 2.1.7 on 2019-03-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='kenofuniverse@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
